### ISSUE TITLE
Le funzioni

### ISSUE THREAD

**Issue by FabioZTessitore** [lucifero55/Funzioni#1]
Ti ho inviato dei file sulle funzioni. Tutte cose che gia' sai, fammi sapere se ok

**Comment by lucifero55** [comment]
Tutto chiaro. 
Solo una cosa, l'uso di putchar() invece di printf(), è qualcosa che converrebbe sempre fare se si dovesse stampare un solo carattere o fa lo stesso?

**Comment by FabioZTessitore** [comment]
si, per un solo carattere conviene putchar perché è più efficiente
