### ISSUE TITLE
i moduli

### ISSUE THREAD

**Issue by FabioZTessitore** [lucifero55/Funzioni#2]
Ho aggiunto una directory moduli, c'è lo stesso programma che calcola operazioni però riscritto in modo da isolare un gruppo di funzioni correlate. Da questo momento in poi i programmi dovrai strutturarli così.

ps: anche il Makefile è un po' piu' completo. Ora tiene traccia delle dipendenze

dimmi se ok

**Comment by lucifero55** [comment]
Tutto ok
