### ISSUE TITLE
Descrizione

### ISSUE THREAD

**Issue by FabioZTessitore** [lucifero55/Funzioni#3]
![es5_32_33](https://cloud.githubusercontent.com/assets/3002194/16176823/fdb4c2a8-3619-11e6-9906-f18a7165580a.png)

**Comment by FabioZTessitore** [comment]
Senza scrivere codice, cerchiamo di capire di quali moduli (un modulo per il momento è un insieme di funzioni corelate) potremmo aver bisogno

**Comment by lucifero55** [comment]
Ho fatto il programma senza moduli. Non avevo letto l'ultimo vostro messaggio xD. 
Non ho però ben capito quali funzioni dovrei creare

**Comment by FabioZTessitore** [comment]
Il programma è fatto bene e possiamo usarlo come punto di partenza.

Come ti dicevo, per il momento dobbiamo considerare un modulo come un insieme di funzioni correlate. L'idea è quella di creare qualcosa di riutilizzabile anche in altri programmi in modo da fare meno fatica e (cosa non meno importante) avere blocchi di codice di cui possiamo fidarci.

Nel programma vengono effettuate tutta una serie di "operazioni" e dobbiamo cercare di raggrupparle; quindi la prima cosa da fare è cercare di capire quali potrebbero essere questi gruppi. Ognuno di loro di cosa dovrebbe occuparsi?

**Comment by lucifero55** [comment]
..aiutino?

**Comment by FabioZTessitore** [comment]
Per esempio, ci sono delle operazioni legate all'estrazione di numeri casuali. Queste operazioni molto probabilmente ti serviranno anche in altri programmi.
Crea allora un file random.h e scrivi i prototipi delle funzioni ricordando che devono essere il più generali possibili (cioè non devono fare solo il lavoro che ti serve per questo programma, ma devono risultare utili in generale)

**Comment by lucifero55** [comment]
Una funzione che chiede in ingresso l'intervallo del numero casuale che riceveremo;
  Es. random(1,23); 
  che ritorna un valore compreso tra 1 e 23

**Comment by FabioZTessitore** [comment]
certamente, ma non solo

**Comment by lucifero55** [comment]
cos'altro?

**Comment by FabioZTessitore** [comment]
faccio tutto io?

**Comment by lucifero55** [comment]
Non ho ben capito come funziona il makefile quando lo uso, potrebbe farmi qualche esempio?

**Comment by lucifero55** [comment]
Tralasciando la mancanza di altre funzioni, il file random.c è strutturato in modo corretto?

**Comment by FabioZTessitore** [comment]
I file random.h e random.c sono strutturati correttamente. La stessa cosa non si può dire della funzione che hai creato. Se la riguardi ti accorgerai che fa più di un'operazione (nel senso che non estrae soltanto un numero compreso nell'intervallo, ma fa anche altro). Allora sarebbe più logico creare un'altra funzione.

ps. Nel file main.c bisogna sfruttare le funzionalità messe a disposizione del modulo random ed evitare di ripetere sempre le stesse operazioni

**Comment by lucifero55** [comment]
Il problema della funzione è che ritorna il valore?

**Comment by FabioZTessitore** [comment]
no. come ti avevo scritto il problema è che fa più di una cosa
(immagina di chiamarla più volte per avere l'estrazione di vari numeri ...)

**Comment by lucifero55** [comment]
Calcola il valore 'max' che serve per ottenere il numero compreso tra i due valori.
Questo è il problema?

**Comment by FabioZTessitore** [comment]
No

Il martedì 16 agosto 2016, lucifero55 <notifications@github.com> ha scritto:

**Comment by lucifero55** [comment]
Rimane solo 'srand'

**Comment by FabioZTessitore** [comment]
eh

**Comment by lucifero55** [comment]
Come va adesso

**Comment by FabioZTessitore** [comment]
please push your code

**Comment by lucifero55** [comment]
i did

**Comment by FabioZTessitore** [comment]
fammi capire ... hai tolto srand() e va bene, ma ora se volessi usare il tuo modulo otterrei sempre la stessa sequenza. Ti pare normale?

**Comment by FabioZTessitore** [comment]
Tazza, lei imbroglia

**Comment by lucifero55** [comment]
ahhaha

**Comment by lucifero55** [comment]
Cosa vuole che faccia?

**Comment by FabioZTessitore** [comment]
Cerchiamo di capirci. Se abbiamo deciso di creare il modulo random è perché non vogliamo usare nel main le funzioni srand e rand (in altre parole dobbiamo nascondere i dettagli della generazione di numeri pseudo casuali)

**Comment by lucifero55** [comment]
Creo una funzione con il solo srand all'interno?

**Comment by FabioZTessitore** [comment]
![moduli](https://cloud.githubusercontent.com/assets/3002194/17698162/bce1d324-63b9-11e6-8eed-4fbe86f7f0b3.png)

**Comment by lucifero55** [comment]
Non ho capito cosa rappresenta il rettangolo giallo

**Comment by FabioZTessitore** [comment]
è un altro modulo che ancora non abbiamo introdotto. Per il momento pensa a random

**Comment by lucifero55** [comment]
Mi viene solo in mente di aggiungere una funzione che al suo interno abbia 'srand'

**Comment by FabioZTessitore** [comment]
we are waiting for your function

**Comment by lucifero55** [comment]
i pushed my code

**Comment by FabioZTessitore** [comment]
ok, va bene ma prima di andare avanti cambia i nomi alle funzioni.
Quella che hai chiamato Srand effettua operazioni preliminari all'uso del modulo. Il nome più adatto potrebbe essere random_init(). L'altra invece potrebbe essere random_between()

**Comment by lucifero55** [comment]
Fatto
