### ISSUE TITLE
Makefile

### ISSUE THREAD

**Issue by FabioZTessitore** [lucifero55/Funzioni#4]
## Il file Makefile

Ti riporto l'esempio che ti ho inviato
```Makefile
CFLAGS=-Wall -ansi -pedantic

# per ottenere il file eseguibile 'operazioni'
# sono necessari i file main.o e operazioni.o
operazioni: main.o operazioni.o

# il file main.o si ottiene a partire da main.c
main.o: main.c
operazioni.o: operazioni.c
```

La prima riga è la solita dichiarazione di variabile CFLAGS che verrà automaticamente utilizzata per la compilazione.

Le righe del tipo:
```Makefile
nomefile.o: nomefile.c
```
significano: "per ottenere il file nomefile.o devi compilare il file nomefile.c"

Più in alto invece trovi:
```Makefile
operazioni: main.o operazioni.o
```
che significa: "per ottenere il file operazioni devi prima ottenere i file main.o e operazioni.o"

### Utilizzo del Makefile
Ogni volta che scrivi una "regola" come quelle dell'esempio tieni traccia delle dipendenze. Se per esempio modifichi il file operazioni.c verrà ricompilato per ottenere operazioni.o (perché operazioni.o "dipende" da operazioni.c).

La prima regola scritta è quella che viene eseguita se non viene specificato diversamente, quindi per compilare il programma basta scrivere
```bash
$ make
```

**Comment by lucifero55** [comment]
capito

**Comment by FabioZTessitore** [comment]
Ho riscritto il Makefile nella cartella moduli rendendo esplicite le regole di compilazione. Fammi sapere se ti è chiaro.

**Comment by lucifero55** [comment]
'operazioni.o: operazioni.c operazioni.h' anche i file .h vanno inseriti nel makefile?

**Comment by FabioZTessitore** [comment]
Se il file operazioni.h cambia, il file operazioni.c che da esso dipende
deve essere ricompilato

Il martedì 16 agosto 2016, lucifero55 <notifications@github.com> ha scritto:

**Comment by FabioZTessitore** [comment]
Per essere più precisi

il file operazioni.o dipende sia da operazioni.c che da operazioni.h

Il mercoledì 17 agosto 2016, Fabio Z Tessitore <fabioztessitore@gmail.com>
ha scritto:

**Comment by lucifero55** [comment]
Capito

**Comment by FabioZTessitore** [comment]
main.o non dipende da random.h
