### ISSUE TITLE
Altri moduli

### ISSUE THREAD

**Issue by FabioZTessitore** [lucifero55/Funzioni#5]
Se ora guardi il main ci troverai dentro tutta una serie di operazioni. In particolare la stampa dei messaggi di risposta esatta e risposta errata sembrano proprio competenza di un modulo di "computer assisted instruction, CAI"

**Comment by lucifero55** [comment]
Devo creare delle funzioni che stampino un determinato messaggio?

**Comment by FabioZTessitore** [comment]
righe 21 e 25 di main.c

**Comment by lucifero55** [comment]
Come ritorno una stringa da una funzione?

**Comment by FabioZTessitore** [comment]
bisogna creare un altro modulo, chiamato cai. In questo modulo per il momento ci saranno le funzioni che danno il messaggio di risposta esatta e quello di risposta errata

**Comment by FabioZTessitore** [comment]
molto bene. Non sapendo come fare a ritornare una stringa hai trovato una valida soluzione alternativa. OK!

Per inciso si fa così:
```C
char* hello() {
    return "Hello";
}```
