### ISSUE TITLE
Come li montiamo questi moduli? hahaha

### ISSUE THREAD

**Issue by FabioZTessitore** [lucifero55/Funzioni#6]
Vatti a rivedere quella immagine che ti ho mandato prima. In questo momento nel tuo main stai usando sia random che cai. La situazione è quella descritta dalla seconda parte del disegno.

Io vorrei arrivare a fare le cose in base allo schema della prima parte. In altre parole random sarà un modulo di base. cai dipende da random per funzionare. Infine main deve usare solo cai (non puoi usare random_init() e random_between() in main)

**Comment by FabioZTessitore** [comment]
Allora ... luci e ombre

Va benissimo una funzione di inizializzazione del modulo cai. Ovviamente il nome potrebbe essere cai_init().

Quello che non va bene è il fatto che faccia due cose (richiama random_init() per poter funzionare e genera i numeri).
Siccome il problema dice che devono essere generati numeri ad una cifra potrebbe essere il caso creare una funzione cai_estrai_cifra() (PS. niente passaggi per riferimento)

Infine qualche aggiustatina a main.c e Makefile

**Comment by lucifero55** [comment]
Se faccio le cose separate è come se creassi una copia di ogni funzione di random.c

**Comment by FabioZTessitore** [comment]
non sono sicuro di aver capito cosa vuoi dire

**Comment by lucifero55** [comment]
E io di ciò che devo fare allora :/

**Comment by FabioZTessitore** [comment]
Provo a ricapitolare

Questo programma è relativamente semplice e potresti fare tutte le operazioni nel main. Lo stiamo dividendo in moduli per farti abituare a ragionare così. Ogni modulo ha delle responsabilità ben precise. Niente di più, niente di meno.

Nel nostro caso abbiamo 3 moduli.

1) il main. La sua responsabilità è quella di mettere insieme i pezzi (le funzionalità) fornite dal modulo cai in modo da portare a termine il compito richiesto. In altre parole deve farsi dare i numeri estratti, chiedere all'utente il risultato, confrontare il risultato vero con quello dell'utente, stampare un opportuno messaggio. (PS. il modulo main NON estrae i numeri, NON decide la stringa da stampare, OK?)

2) cai. Questo modulo mette a disposizione di main le funzionalità di cui quest'ultimo ha bisogno. Se hai letto attentamente quanto scritto sopra vedrai che le responsabilità di cai sono quelle di estrarre una cifra e decidere quali stringhe stampare in caso di risposta esatta o errata. (PS. cai non ha idea di come verranno combinate queste cose per ottenere il risultato finale, questo è compito di main)

3) random. Questo modulo fornisce a cai delle funzioni "facili da usare" per la generazione di numeri psudocasuali (PS non ha idea di cosa ci farà cai)

**Comment by lucifero55** [comment]
Ho creato main2.c che dovrebbe mostrare come dovrebbe essere il main a lavoro finito. 
Inutile lavorare sulle funzioni se non so prima cosa serva al main.

**Comment by FabioZTessitore** [comment]
va abbastanza bene

dovresti togliere l'include "random.h" perché nel main non chiami nessuna funzione di random. Poi le funzioni question ecc ecc dovrebbero avere il nome preceduto da cai_

**Comment by FabioZTessitore** [comment]
finalmente ci siamo, giusto per concludere le funzioni di cai dovrebbero restituire le stringhe non stamparle direttamente loro (in questo modo se cambi il modo di stampare per esempio usando le ncurses, cai non cambia)

una funzione che restituisce una stringa è del tipo
char* foo();

**Comment by FabioZTessitore** [comment]
in cai va bene, devi solo farlo anche per le altre funzioni.

in main invece la stringa non la stampi!!!

**Comment by lucifero55** [comment]
e come devo fare?

**Comment by FabioZTessitore** [comment]
per stampare una stringa puoi usare 
```c
puts(stringa);
```
oppure
```c
printf("%s", stringa);
```

**Comment by lucifero55** [comment]
non ho fatto così: "printf("%s", stringa);"?

**Comment by lucifero55** [comment]
come dovrei effettivamente scrivere?

**Comment by FabioZTessitore** [comment]
si scusa ho visto main2
cancella i file non necessari, usa gitignore (per l'eseguibile), guarda cosa ho scritto nell'altra issue a proposito del makefile

**Comment by lucifero55** [comment]
Devo cambiare anche cai_Question?
se si come?

**Comment by FabioZTessitore** [comment]
non hai ancora studiato con me come si fa quindi lascia stare

**Comment by FabioZTessitore** [comment]
ok, finito

alla fine di questa esercitazione travagliata senti di aver appreso qualcosa? come ti è parsa?

**Comment by lucifero55** [comment]
Senza dubbio, avendo capito quanto ti semplifica la vita questo tipo di programmazione, mi sento molto più propenso a scrivere programmi molto più complessi senza la paura di non capirci niente a lavoro finito.

Credo sia un bel passo avanti.
