### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by lucifero55** [lucifero55/Funzioni#7]
![schermata del 2016-08-28 23-48-49](https://cloud.githubusercontent.com/assets/16176113/18037093/137f60e0-6d7c-11e6-82ec-5da3ad12474d.png)
![schermata del 2016-08-28 23-49-18](https://cloud.githubusercontent.com/assets/16176113/18037095/14d92804-6d7c-11e6-83d3-e8a7e5445895.png)

Installato ubuntu gnome 16.04 con questo terminale bianco. 
A dirla tutta mi piace molto, solo che usando nano il colore giallo mi risulta difficile da leggere.

**Comment by FabioZTessitore** [comment]
e perché usi nano?

2016-08-29 0:06 GMT+02:00 lucifero55 <notifications@github.com>:
